// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvAF5q7UwWMCtJ4NoZ5YFOUioXlUtsdP4',
    appId: '1:498639080180:web:da284575adb2ae56832ca1',
    messagingSenderId: '498639080180',
    projectId: 'livro-b0d41',
    authDomain: 'livro-b0d41.firebaseapp.com',
    storageBucket: 'livro-b0d41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZjztm0obK9AQ1nEj6k4gMNFM9IJdat8',
    appId: '1:498639080180:android:1f9584446cd3df08832ca1',
    messagingSenderId: '498639080180',
    projectId: 'livro-b0d41',
    storageBucket: 'livro-b0d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNyxXdKcncKKVdJdltni5LbFRveXhxJE',
    appId: '1:498639080180:ios:c62f2f5dfa726946832ca1',
    messagingSenderId: '498639080180',
    projectId: 'livro-b0d41',
    storageBucket: 'livro-b0d41.firebasestorage.app',
    iosBundleId: 'com.example.antologiaNueva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqNyxXdKcncKKVdJdltni5LbFRveXhxJE',
    appId: '1:498639080180:ios:c62f2f5dfa726946832ca1',
    messagingSenderId: '498639080180',
    projectId: 'livro-b0d41',
    storageBucket: 'livro-b0d41.firebasestorage.app',
    iosBundleId: 'com.example.antologiaNueva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvAF5q7UwWMCtJ4NoZ5YFOUioXlUtsdP4',
    appId: '1:498639080180:web:ea535fd02505f3d4832ca1',
    messagingSenderId: '498639080180',
    projectId: 'livro-b0d41',
    authDomain: 'livro-b0d41.firebaseapp.com',
    storageBucket: 'livro-b0d41.firebasestorage.app',
  );
}
